# Generated by Django 5.0.6 on 2024-11-27 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_title', models.CharField(max_length=255)),
                ('event_description', models.TextField()),
                ('skills_required', models.TextField()),
                ('event_category', models.CharField(max_length=100)),
                ('event_date', models.DateTimeField()),
            ],
        ),
    ]
