# Generated by Django 5.0.6 on 2024-11-26 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('mentee', 'Mentee'), ('mentor', 'Mentor')], max_length=10)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('education', models.CharField(blank=True, max_length=255, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('preferred_days', models.CharField(blank=True, max_length=255, null=True)),
                ('company_affiliation', models.CharField(blank=True, max_length=255, null=True)),
                ('role_at_company', models.CharField(blank=True, max_length=255, null=True)),
                ('professional_expertise', models.TextField(blank=True, null=True)),
                ('area_of_interest', models.CharField(blank=True, max_length=255, null=True)),
                ('preferred_communication', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
